name: event_with_thong
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  logger: ^2.5.0
  intl: ^0.20.1
  provider: ^6.1.2
  flutter_svg: ^2.0.16
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.1.3
  carousel_slider: ^5.0.0
  auto_scroll: ^0.2.0
  scroll_to_index: ^3.0.1
  photo_view: ^0.15.0
  flutter_staggered_grid_view: ^0.7.0
  uuid: ^4.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.3
  flutter_slidable: ^3.1.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  # flutter_launcher_icons: ^0.14.2

dev_dependencies:
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:

    - assets/
    - assets/Icon/
    - assets/image/
    - assets/logo/
    - assets/welcomeScreen/
    - assets/background/
    - assets/vendor/
    - assets/warningIcon/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 200
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # see https://flutter.dev/custom-fonts/#from-packages
  # For details regarding fonts from package dependencies,
